# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:56
from __future__ import unicode_literals
import os
from sys import path
from django.core.management import call_command
from django.core import serializers
from django.db import migrations



def load_fixture(apps, schema_editor):
    call_command('loaddata', 'users.json', app_label='api') 
    call_command('loaddata', 'products.json', app_label='api') 
    call_command('loaddata', 'orders.json', app_label='api') 
    call_command('loaddata', 'carts.json', app_label='api') 

def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    Customer = apps.get_model("api", "Customer")
    Customer.objects.all().delete()

class Migration(migrations.Migration):  

    dependencies = [
        ('api', '0005_orderproduct'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]